### ISSUE TITLE
Is env var JFROG_CLI_REPORT_USAGE still valid?

### ISSUE THREAD

**Issue by rpjday** [jfrog/documentation#153]
In online docs, the page that lists some of the env vars mentions JFROG_CLI_REPORT_USAGE, but that variable does not show up in the output of "jf options".

**Comment by eyalbe4** [comment]
Yes - 
This environment variable is in use by JFrog CLI - 
https://github.com/search?q=repo%3Ajfrog%2Fjfrog-cli-core%20JFROG_CLI_REPORT_USAGE&type=code
I'm closing this issue, since the option for opening issues in this repository will be soon cancelled.
You're welcome to open issues for JFrog CLI in github.com/jfrog/jfrog-cli
